name: incentivesgit
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  intl: ^0.19.0
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.3
  connectivity_plus: ^5.0.2
  package_info_plus: ^8.0.0
  firebase_core: ^2.31.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  country_pickers: ^2.0.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  http: ^1.2.1
  flutter_spinkit: ^5.2.1
  syncfusion_flutter_gauges: 25.1.42
  file_picker: ^8.0.3
  any_animated_button: ^0.0.4
  url_launcher: ^6.2.6
  carousel_slider: ^4.2.1
  popover: ^0.3.0+1
  webview_flutter: ^4.7.0
  video_player: ^2.1.8
  chewie: ^1.0.0
  flutter_pdfview: ^1.3.2
  audioplayers: ^6.0.0
  just_audio: ^0.9.38
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.1.0
  expandable_text: ^2.3.0
  get_storage: ^2.1.1
  skeleton_loader: ^2.0.0+4
  flutter_otp_text_field: ^1.1.3+2
  qr_flutter: ^4.1.0
  expandable: ^5.0.1
  qr_code_scanner: ^1.0.1
  flutter_html: 3.0.0-beta.2
  timeline_tile: ^2.0.0
  record: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true


  assets:
      - assetes/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assetes/fonts/Poppins-MediumItalic.ttf
        # - asset: fonts/Schyler-Italic.ttf
          style: italic
    - family: Segoe UI
      fonts:
        - asset: assetes/fonts/segoeuithibd.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
